on: push
jobs:
  jobs1:
    name: "jobs1"
    runs-on: windows-latest
    steps:
    - run: pwd
    - run: pacman -S git
  jobs2:
    name: "jobs2"
    runs-on: windows-latest
    steps:
    - run: ls
